### ISSUE TITLE
How to print something on crawler hit with middleware?

### ISSUE THREAD

**Issue by Aditya94A** [JefferyHus/es6-crawler-detect#16]
I'd rather not manage crawler instances and manually log for all my APIs,

I was wondering if there were a way to do something like

```
app.use(middleware(req=>console.log("Got crawler request!", req));
```

Is there a way to do this? Or am I missing something?

I'm not sure what the current middleware does. It seems to just instantiate a Crawler instance: https://github.com/JefferyHus/es6-crawler-detect/blob/b75ebdb6a010d29848b0b7f8b242197a56f37fc2/src/index.js

**Comment by JefferyHus** [comment]
Yes the middle-ware objective is to allow you to use the crawler instance within your request object, instead of initiating it every time.

If I understand your demand, I think you would like to send a callback to be executed every time the middle-ware runs. If that's correct I may think of a solution, if that's not the case please elaborate more.

**Comment by Aditya94A** [comment]
Yes, an optional callback that can be provided alongside setting up `middleware` in `app.use` (as in example above) would be really fantastic as it would give us a single place to manage/track hits by crawlers 😄
